name: grocify
description: Groceries shopping app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  video_player: ^2.9.2
  go_router: ^10.1.2
  model:
    path: api/packages/model
  http: ^1.2.2
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  intl: ^0.19.0
  bloc: ^8.1.4
  # mobile_scanner: ^6.0.2
  mobile_scanner: ^3.5.1
  flutter_animate: ^4.5.0
  google_fonts: ^6.1.0
  #  数据库
  sqlite3: ^2.4.7
  oktoast: ^3.4.0
  uuid: ^4.0.0
  pretty_qr_code: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/videos/
    - assets/images/
